### PR TITLE
await selector function

### PR DESCRIPTION
**Pull request by dokithonon**
By doing this we can use async function in the selector function on the server

### CODE REVIEW

**Comment by dokithonon** [comment]
@jankapunkt Hello Jan. What do you think of this request ?

**Comment by lynchem** [comment]
Looks good @dokithonon , while we're making the update I'd say `allow` `changeSelector` & `customSearch` also need awaits to allow using collections or other async apis inside them.

**Comment by dokithonon** [comment]
@lynchem thanks for looking at it. I have also awaited the function your are pointing. I was not using them so did not know what they were doing.

**Comment by lynchem** [comment]
That looks good to me, thanks for updating them all. I think we can merge and hopefully @jankapunkt can review in the merge to master & release.

**Comment by jankapunkt** [comment]
Published via `aldeed:tabular@3.0.0-rc.2`

**Pull request merged**
