### PR TITLE
fix: sanitize data for xss

### PR DESCRIPTION
**Pull request by guncebektas**
possible fix for https://github.com/Meteor-Community-Packages/meteor-tabular/issues/331

### CODE REVIEW

**Comment by guncebektas** [comment]
I wrote the test but couldn't run it. Can you check it pls?

**Comment by guncebektas** [comment]
I found a bug if the column has json object :( I will try to fix this

**Comment by jankapunkt** [comment]
Hey @guncebektas I think I remember that Blaze already had sanitizer functionality built into it. Maybe you can first check if this is true and if so favour it's implementation.

**Comment by guncebektas** [comment]
I found the code in blaze. I think its not sanitizing json objects. I'm working on on a fix and will create a pr.

**Pull request closed without merging**
